---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zk0
  namespace: martin
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: foo.io
      advertisedURL:
        enabled: true

