---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zk0
  namespace: confluent
  annotations:
    platform.confluent.io/pod-overlay-configmap-name: dns-overlay-cm
    platform.confluent.io/zookeeper-myid-offset: "0"
spec:
  replicas: 2
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: foo.io
      advertisedURL:
        enabled: true
        prefix: zk0-
      prefix: zk0-
  peers:
    - server.0=0.0.0.0:2888:3888
    - server.1=0.0.0.0:2888:3888
    - server.2=zk2-0.zk2.foo.io:2888:3888
---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zk1
  namespace: confluent
  annotations:
    platform.confluent.io/pod-overlay-configmap-name: dns-overlay-cm
    platform.confluent.io/zookeeper-myid-offset: "2"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: foo.io
      advertisedURL:
        enabled: true
        prefix: zk1-
      prefix: zk1-
  peers:
    - server.0=zk0-0.zk0.foo.io:2888:3888
    - server.1=zk0-1.zk1.foo.io:2888:3888
    - server.2=0.0.0.0:2888:3888

