---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zk-source
  namespace: confluent
  annotations:
    platform.confluent.io/pod-overlay-configmap-name: dns-overlay-cm
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.8.0
    init: confluentinc/confluent-init-container:2.10.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: foo.io
      advertisedURL:
        enabled: true
        prefix: zk-source-
  peers:
    - server.0=zk-source-0.zk-source.confluent.svc.cluster.local:2888:3888
    - server.1=zk-source-1.zk-source.confluent.svc.cluster.local:2888:3888
    - server.2=zk-source-2.zk-source.confluent.svc.cluster.local:2888:3888
